# readthedocs now requires that you barf this into your project root or else it will refuse to function
version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
formats: all
sphinx:
  configuration: docs/conf.py
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - webpush
        - blurhash
        - test
        - docs
        